image: gitpod/workspace-dotnet-vnc

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Build and Restore
    init: dotnet restore && dotnet build # runs during prebuild

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 6080
    onOpen: open-browser

vscode:
  extensions:
    - muhammad-sammy.csharp
